service: todo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://kloudy-todos-api.netlify.app/
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
  environment:
    TODOS_TABLE: ${self:service}-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt:
                - TodosTable
                - Arn

functions:
  createTodo:
    handler: src/handlers/createTodo.handler
    events:
      - httpApi:
          path: /todos
          method: post

  getTodos:
    handler: src/handlers/getTodos.handler
    events:
      - httpApi:
          path: /todos
          method: get

  updateTodo:
    handler: src/handlers/updateTodo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: put

  deleteTodo:
    handler: src/handlers/deleteTodo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: delete

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE
plugins:
  - serverless-s3-sync
